//
// Brought to Teensy-wells v1.0.0 on Wed May 05 2026 by APM
//
// @developers: Adam Micolich
//
// Basic algorithm for testing all 42 GPIO pins.
// It will cycle through bringing all pins up, all pins down, and do it enough times to catch each one.
// Has no interaction with PyNE-wells code, it's purely for hardware test, and should only be used with the Teensy on bench not in the MuxBox.
//

int led1Pin = 1;
int led2Pin = 2;
int led3Pin = 3;
int led4Pin = 4;
int led5Pin = 5;
int led6Pin = 6;
int led7Pin = 7;
int led8Pin = 8;
int led9Pin = 9;
int led10Pin = 10;
int led11Pin = 11;
int led12Pin = 12;
int led13Pin = 13;
int led14Pin = 14;
int led15Pin = 15;
int led16Pin = 16;
int led17Pin = 17;
int led18Pin = 18;
int led19Pin = 19;
int led20Pin = 20;
int led21Pin = 21;
int led22Pin = 22;
int led23Pin = 23;
int led24Pin = 24;
int led25Pin = 25;
int led26Pin = 26;
int led27Pin = 27;
int led28Pin = 28;
int led29Pin = 29;
int led30Pin = 30;
int led31Pin = 31;
int led32Pin = 32;
int led33Pin = 33;
int led34Pin = 34;
int led35Pin = 35;
int led36Pin = 36;
int led37Pin = 37;
int led38Pin = 38;
int led39Pin = 39;
int led40Pin = 40;
int led41Pin = 41;
int counter = 0;
int wait = 100;
bool hasRun = false;

void setup() {
  // initialize the digital pins as outputs
  pinMode(led1Pin,OUTPUT);
  pinMode(led2Pin,OUTPUT);
  pinMode(led3Pin,OUTPUT);
  pinMode(led4Pin,OUTPUT);
  pinMode(led5Pin,OUTPUT);
  pinMode(led6Pin,OUTPUT);
  pinMode(led7Pin,OUTPUT);
  pinMode(led8Pin,OUTPUT);
  pinMode(led9Pin,OUTPUT);
  pinMode(led10Pin,OUTPUT);
  pinMode(led11Pin,OUTPUT);
  pinMode(led12Pin,OUTPUT);
  pinMode(led13Pin,OUTPUT);
  pinMode(led14Pin,OUTPUT);
  pinMode(led15Pin,OUTPUT);
  pinMode(led16Pin,OUTPUT);
  pinMode(led17Pin,OUTPUT);
  pinMode(led18Pin,OUTPUT);
  pinMode(led19Pin,OUTPUT);
  pinMode(led20Pin,OUTPUT);
  pinMode(led21Pin,OUTPUT);
  pinMode(led22Pin,OUTPUT);
  pinMode(led23Pin,OUTPUT);
  pinMode(led24Pin,OUTPUT);
  pinMode(led25Pin,OUTPUT);
  pinMode(led26Pin,OUTPUT);
  pinMode(led27Pin,OUTPUT);
  pinMode(led28Pin,OUTPUT);
  pinMode(led29Pin,OUTPUT);
  pinMode(led30Pin,OUTPUT);
  pinMode(led31Pin,OUTPUT);
  pinMode(led32Pin,OUTPUT);
  pinMode(led33Pin,OUTPUT);
  pinMode(led34Pin,OUTPUT);
  pinMode(led35Pin,OUTPUT);
  pinMode(led36Pin,OUTPUT);
  pinMode(led37Pin,OUTPUT);
  pinMode(led38Pin,OUTPUT);
  pinMode(led39Pin,OUTPUT);
  pinMode(led40Pin,OUTPUT);
  pinMode(led41Pin,OUTPUT);
}

void loop() {
  if (!hasRun){
    digitalWrite(led1Pin,HIGH);
    delay(wait);
    digitalWrite(led2Pin,HIGH);
    delay(wait);
    digitalWrite(led3Pin,HIGH);
    delay(wait);
    digitalWrite(led4Pin,HIGH);
    delay(wait);
    digitalWrite(led5Pin,HIGH);
    delay(wait);
    digitalWrite(led6Pin,HIGH);
    delay(wait);
    digitalWrite(led7Pin,HIGH);
    delay(wait);
    digitalWrite(led8Pin,HIGH);
    delay(wait);
    digitalWrite(led9Pin,HIGH);
    delay(wait);
    digitalWrite(led10Pin,HIGH);
    delay(wait);
    digitalWrite(led11Pin,HIGH);
    delay(wait);
    digitalWrite(led12Pin,HIGH);
    delay(wait);
    digitalWrite(led13Pin,HIGH);
    delay(wait);
    digitalWrite(led14Pin,HIGH);
    delay(wait);
    digitalWrite(led15Pin,HIGH);
    delay(wait);
    digitalWrite(led16Pin,HIGH);
    delay(wait);
    digitalWrite(led17Pin,HIGH);
    delay(wait);
    digitalWrite(led18Pin,HIGH);
    delay(wait);
    digitalWrite(led19Pin,HIGH);
    delay(wait);
    digitalWrite(led20Pin,HIGH);
    delay(wait);
    digitalWrite(led21Pin,HIGH);
    delay(wait);
    digitalWrite(led22Pin,HIGH);
    delay(wait);
    digitalWrite(led23Pin,HIGH);
    delay(wait);
    digitalWrite(led24Pin,HIGH);
    delay(wait);
    digitalWrite(led25Pin,HIGH);
    delay(wait);
    digitalWrite(led26Pin,HIGH);
    delay(wait);
    digitalWrite(led27Pin,HIGH);
    delay(wait);
    digitalWrite(led28Pin,HIGH);
    delay(wait);
    digitalWrite(led29Pin,HIGH);
    delay(wait);
    digitalWrite(led30Pin,HIGH);
    delay(wait);
    digitalWrite(led31Pin,HIGH);
    delay(wait);
    digitalWrite(led32Pin,HIGH);
    delay(wait);
    digitalWrite(led33Pin,HIGH);
    delay(wait);
    digitalWrite(led34Pin,HIGH);
    delay(wait);
    digitalWrite(led35Pin,HIGH);
    delay(wait);
    digitalWrite(led36Pin,HIGH);
    delay(wait);
    digitalWrite(led37Pin,HIGH);
    delay(wait);
    digitalWrite(led38Pin,HIGH);
    delay(wait);
    digitalWrite(led39Pin,HIGH);
    delay(wait);
    digitalWrite(led40Pin,HIGH);
    delay(wait);
    digitalWrite(led41Pin,HIGH);
    delay(wait);
    digitalWrite(led1Pin,LOW);
    delay(wait);
    digitalWrite(led2Pin,LOW);
    delay(wait);
    digitalWrite(led3Pin,LOW);
    delay(wait);
    digitalWrite(led4Pin,LOW);
    delay(wait);
    digitalWrite(led5Pin,LOW);
    delay(wait);
    digitalWrite(led6Pin,LOW);
    delay(wait);
    digitalWrite(led7Pin,LOW);
    delay(wait);
    digitalWrite(led8Pin,LOW);
    delay(wait);
    digitalWrite(led9Pin,LOW);
    delay(wait);
    digitalWrite(led10Pin,LOW);
    delay(wait);
    digitalWrite(led11Pin,LOW);
    delay(wait);
    digitalWrite(led12Pin,LOW);
    delay(wait);
    digitalWrite(led13Pin,LOW);
    delay(wait);
    digitalWrite(led14Pin,LOW);
    delay(wait);
    digitalWrite(led15Pin,LOW);
    delay(wait);
    digitalWrite(led16Pin,LOW);
    delay(wait);
    digitalWrite(led17Pin,LOW);
    delay(wait);
    digitalWrite(led18Pin,LOW);
    delay(wait);
    digitalWrite(led19Pin,LOW);
    delay(wait);
    digitalWrite(led20Pin,LOW);
    delay(wait);
    digitalWrite(led21Pin,LOW);
    delay(wait);
    digitalWrite(led22Pin,LOW);
    delay(wait);
    digitalWrite(led23Pin,LOW);
    delay(wait);
    digitalWrite(led24Pin,LOW);
    delay(wait);
    digitalWrite(led25Pin,LOW);
    delay(wait);
    digitalWrite(led26Pin,LOW);
    delay(wait);
    digitalWrite(led27Pin,LOW);
    delay(wait);
    digitalWrite(led28Pin,LOW);
    delay(wait);
    digitalWrite(led29Pin,LOW);
    delay(wait);
    digitalWrite(led30Pin,LOW);
    delay(wait);
    digitalWrite(led31Pin,LOW);
    delay(wait);
    digitalWrite(led32Pin,LOW);
    delay(wait);
    digitalWrite(led33Pin,LOW);
    delay(wait);
    digitalWrite(led34Pin,LOW);
    delay(wait);
    digitalWrite(led35Pin,LOW);
    delay(wait);
    digitalWrite(led36Pin,LOW);
    delay(wait);
    digitalWrite(led37Pin,LOW);
    delay(wait);
    digitalWrite(led38Pin,LOW);
    delay(wait);
    digitalWrite(led39Pin,LOW);
    delay(wait);
    digitalWrite(led40Pin,LOW);
    delay(wait);
    digitalWrite(led41Pin,LOW);
    delay(wait);
    counter++;  
    hasRun = true;
  }  
}